### PR TITLE
fix(layoutMapper): add title, description

### PR DESCRIPTION
**Pull request by rvsia**
It doesn't look right, but right now it's just a quick fix, I will investigate later

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia why is there yarn.lock?

**Comment by rvsia** [comment]
@Hyperkid123 I dont know why yarn.lock is there, so I will remove it!

**Comment by rvsia** [comment]
@Hyperkid123 Removed! For some reason git is watching the file even the file is in .gitignore :disappointed:

**Comment by Hyperkid123** [comment]
I will check whats going o  tomorrow

**Pull request merged**
